### ISSUE TITLE
Error in running training script for AC3/AC4

### ISSUE THREAD

**Issue by PG-Gu** [weih527/Pixel-Embedded-Affinity#2]
Dear authors,

I pulled the docker image as what is suggested in the introduction and run the scripts using a container create from it.
I installed waterz and elf as instructed.
I met an error when I was running the training script for AC3/AC4 using this line 
`python main.py -c=ac3ac4`
Then it threw this error:
`(base) root@afbe65ff1f4d:~/Pixel-Embedded-Affinity/scripts_ac3ac4# python main.py -c=ac3ac4
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    from utils.lmc import mc_baseline
  File "/root/Pixel-Embedded-Affinity/scripts_ac3ac4/utils/lmc.py", line 2, in <module>
    import elf.segmentation.multicut as mc
  File "/root/elf/elf/segmentation/__init__.py", line 12, in <module>
    from .gasp import GaspFromAffinities, run_GASP
  File "/root/elf/elf/segmentation/gasp.py", line 13, in <module>
    from affogato.segmentation import compute_mws_segmentation_from_affinities
ImportError: cannot import name 'compute_mws_segmentation_from_affinities' from 'affogato.segmentation' (/src/anaconda3/lib/python3.7/site-packages/affogato/segmentation/__init__.py)`
I checked by input:
`import affogato.segmentation`
And no error occured.
It seems that compute_mws_segmentation_from_affinities module doesn't exist in affogato.segmentation.
Could you please provide a fix for this?
Thanks in advance

**Comment by weih527** [comment]
elf is already installed in the image by default. There is no need to install it in the image again.

Waterz is installed in python2 by default. If you want to use it in python3, you just need to run the following command:
pip install waterz
